before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HSUy8S9UBblV2r1rk9IiIawL8UJxE8X07/nMfrf7meAQvQY1b71uAuv5DAturnfNqvp1DmDQnEzJsP4yPUf0gwiNuGZrImUMB91GAYwyq7sudv8SIPxC/EDR4hsPUgKiDLbGzY3wpG6MDbParqaHxTwSdsTHmHUxhIfAdGDuQTpL4HJHQmqjUA9JKsQmtWSWZGHOJWT8im2CRGuTsNsHZHZuEQHvo9N08ntPpA104hi8+E6wZ1j+plFLf4LeQJ+TU87/JmpebjKANXWQoyNWZafxKjBjkOVsmIzg2sXZ7/ammldSXd5d78/4ntLUBfuL2ytAYusgW1UIIwGyEQbcHJS77xyWMqkN6CDO1E824RGWLRQv0H7w/G5/y0MHe5wjPm5s8jEim0nooaYZit7fiEU0Z4wzhGC0fy3/+NJ+uo61hYXZ4x7I95eOzGdI1m7bzjUnm3yEcM9OiO1xV7Vr77rmvnNIDiwmlb3cBLCgENty9hjOEq2H1fMTLDN96cfiZUQIah9XsVbwFFO33emu+tnbQsDaiARfEMMnxuaKmUEsaGNLBQiaGTviXkfrxp9WAa8ED1cYP9mQxBrQFhzvObc9PYiHBXFEbKiz6MAun1UPN2jjOVa+b3OLmR/L8R0vj9bDJzURR2fBm1dYS7ypX7K6llHMXfhPQh0yMfhmZrU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
